### ISSUE TITLE
Let's implement this

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-directory#1]
The README.md is the specification. I forked the javascript boilerplate.

**Comment by j3k0** [comment]
(I assigned myself to remember to assign @elmigranto when he joins the project)

**Comment by j3k0** [comment]
Also backport https://github.com/j3k0/ganomede-boilerplate/issues/1

**Comment by elmigranto** [comment]
So this is basically auth server, it handles: 
  - registration (info -> user record in db);
  - profile updates;
  - logins (password -> token);
  - lookups (via user id, auth token, or alias).

User records are couchdb documents, everything else is couch db views mapping different things (authtoken, alias type + value) to user id. Questions:

  - uniqueness
    - auth tokens:
      - generated for first login in directory service, and stored in its couch to ensure uniquness and map to user;
      - when some service (e.g. chat) authenticates user, it either looks it in its own redis auth db, or asks directory services for userid;
    - aliases: what if we have 2 henrys? (`name: henry`) — why uniquness here?
    - do we have single instance of couchdb? if not, how do we ensure any uniquness? couchids are guranteed to be unique? if we have single couchdb wouldn't all of this make sense as sql, I doubt we'll have amount of data that'll make postgres choke, but handling all the relations (mappings to user id) is trivial, uniqueness is easily achieved with indexes, lookups are simpler (`select from aliases join on users…`).

Also, ganomede metadata can be simple `entity–attribute–value` table (`user-id` + `meta name` + `value`) with easy selects (or just make it rows, really). Different apps can use same user record too but add specific data via separate table.

Probably same with facebook auth, maybe we event want single Facebook application to manage auth across all apps. Can be own service, but same db.

We can still have different services (so auth works if metadata dies, etc.) talking to same db, with perhaps own cache (for faster accesing from different geographical regions).

<hr/>

You write in j3k0/ganomede-users#9 about parent-child metadata servers, I guess that is about App A having special meta field not accessible by App B? Wouldn't this be more straightforward with app-specific data that has foreign key to user id and App B can only read rows where (`app=B`). 

If we want to give access to particular meta fields to multiple apps, we can create DB role that can access particular rows and requests from cleared apps are ran with that role.

<hr/>

I guess what I am saying is this looks a lot like reinventing stuff in app code. Why not have single users database where all the data consistency (uniquness, etc) is handled for us?

**Comment by j3k0** [comment]
> User records are couchdb documents, everything else is couch db views mapping different things (authtoken, alias type + value) to user id.

Not necessarly (discussion at the end of this message), also auth token are not part of couchdb. Why?

 - all data but auth tokens are extremely static
   - you can't remove or edit data to a user record, just add data (we will get back to that in the discussion about internal schema).
 - authentication token are volatile (they expire)
 - authentication token are checked very (very!) often, on almost every request (that's a million time per hour at current rate), thus an in-memory database is better for that
 - it's a very good thing that we keep backward compatibility with the current authdb database
   - current authdb maps "token" to "username" (the old name for user id), so we're good
   - so there's no hurry to update all services

> uniqueness of auth tokens:

Pick a random UUID, statisticians have proved that there's basically no chance of picking 2 identical (when picking 1 every ms for the next few millions of years)...

> aliases: what if we have 2 henrys? (`name: henry`) — why uniquness here?

Because it's gonna be convenient for what we are trying to achieve. A use case: invite "henry" to a game, you're guaranteed to have invited who you were trying to: no ambiguity. "henry" will always refer to the same user. Knowing that, data can also be easily cached if needed.

EDIT: if we want something that doesn't have to be unique across all users, in our system it's a metadata and not an alias.

> do we have single instance of couchdb?

Yes (or like so: multiple instances with bi-directional replication, which means exactly the same content on all DBs).

I also come back to this reason often: I don't want to multiply the number of technologies we rely on. When Redis and CouchDB can do, we won't introduce something new in the architecture.

> ganomede metadata ... different apps can use same user record too but add specific data via separate table.

No, because in the end different apps will run in different servers/clusters with no direct access to their respective databases. Example of apps fully separated from each other, but relying on each other's services.

 - "accounts"
   - running "ganomede-directory, ganomede-metadata, ganomede-avatars (on their own databases)
 - "game 1"
   - runs ganomede-metadata (on his own database) + many other things
   - does not run ganomede-directory (ganomede-user will use directory from "accounts")
 - "website"
   - use "accounts" public API for auth tokens validation, users, avatars
   - use "game 1" public API for spending virtual currency
 - ...

The client for game 1 will call ganomede-metadata:

 - from "accounts" for shared stuff
   - examples: country, date of birth)
 - from "game 1" (at a different URL) for app specific stuff
   - examples: audio settings, puzzle progression, ...

> Probably same with facebook auth ... can be own service, but same db.

Here we will have a different facebook app for each app. Also apps can't share their DBs, but users's Facebook IDs will be stored in the global ganomede-directory (acting like a shared DB in a sense).

> You write in j3k0/ganomede-users#9 about parent-child metadata servers

I dropped that idea. It's unnecessarly complex. I need to update the related ganomede-issue,

It's now a central "ganomede-directory", a central "ganomede-metadata" + satellite "ganomede-metadata" for each app. This will work just fine and adds no complexity. (we will extract ganomede metadata as a standalone service: https://github.com/j3k0/ganomede-users/issues/16)

About reinventing the well: I wondered if the whole "ganomede-directory" isn't something we could find an open-source equivalent? But after looking a bit our options I didn't find a good fit for our use case. If you know something let me know!

#### Uniqueness and CouchDB

As mentioned, we don't necessarly have to store 1 document per user. Since user data is purely incremental, we can store documents as such:

| id | value |
|---|---|
| `["id","alice01"]` | `{ "password": "long-hash", "date": 142120994 }` |
| `["aliases","name","Alice"]` | `{ "id": "alice01", "date": 142121004, "public": true }` |
| `["aliases","email","alice@email.com"]` | `{ "id": "alice01", "date": 142121009, "public": false }` |
| `["aliases","name","AliceC"]` | `{ "id": "alice01", "date": 142121017, "public": true }` |
| | etc. |

This way, it's not possible to create 2 identical aliases. No views to retrieve the user id from the aliases, but we need a reducer to get the user's full details from the different documents (`map` emits all docs with user id as the key, `reduce` concatenate aliases: it's not really more complex than writing the SQL join request).

This looks a lot like a relational database, but it's not complex and couchdb have advantages in terms of deployment and operational simplicity that we want to keep benefiting from.

**Comment by j3k0** [comment]
I know I've said that 1 user = 1 document in the README.md, and now I say the opposite. It's still open for discussion, now I find the later solution indeed solves the issues you raised nicely.

**Comment by elmigranto** [comment]
So for uniqueness we have id that is like redis keys (in terms of joined parts, since couch IDs are string-only), and then we have a bunch of docs like:

  - `{"_id": "ids:alice", /* genera user things... */}`;
  - `{"_id": "aliases:alias-type:alias-value", /* alias info with "FK" to "ids:alice"... */}`;
  - `{"_id": "something:else:alice", /* some stuff with "FK" to "ids:alice" */}`.

Then we have views:

  - `profile` keyed `user-id` and value is all those `alice` objects joined into hash of our liking;
  - ~~`aliases` keyed `[type, value]` and value is user id~~ (not needed, just fetch doc with ID `aliases:type:value`).

Looks weird, but I guess it's just me and this is common place for couch.

<hr/>

> *single couch or* multiple instances with bi-directional replication

This mean manual resolution of conflicts, doesn't it? If I remember couch docs correctly, it picks up earlier doc and stores later duplicates as invisible? But then again, not sure what the deal would be with SQL, though we won't probably need multiple write-able servers.

> This looks a lot like a relational database, but it's not complex and couchdb have advantages in terms of deployment and operational simplicity

Not sure I agree here. My guess would be there is a docker image of Postgres ready to go with all the config required is to point it to directory in which data will be stored (and all the universal DB things like allow it to have X ram, etc.). Maybe migrations could be a problem, but I think it is not worse than our `DbComparator` class for replacing designs/views :)

When I look at pros of SQL, I have easier uniqueness with guranteed consistency (FK), more straightforwrad schema (probably just me for lack of couch experience), there is stuff like materialized views/triggers if joins are the problem (but that's getting a bit ahead).

For couch: we already have it.

<hr/>

**About auth tokens.** I'm wondering, are they in the redis cluster that is accessible to every app through its slave and will be propagated down from this service's master?

<hr/>

So, I kinda see what you're going for now (central auth/register + common user data and per app things with everything else), thanks for explaining. To start, I'll try to outline Couch stuff, I guess, and we'll see what we ending up with.

**Comment by elmigranto** [comment]
My problem with couch is that I view it as append-only list of documents with views derived from it; and inventing relations and data constraints/validations *feels* wrong to me, but "yeah, well, that's just, like, my opinion, man" :)

**Comment by elmigranto** [comment]
Which couch version do we use, 1.x or 2.x?

**Comment by j3k0** [comment]
Let's stick to couchDB 1.x, I don't want to have to upgrade our live DB.

*SQL would be a better fit to this task, no question about it. The reason why I want couchdb is because, in the grand scheme of things, we have built a system based on Redis and Couchdb.

Our goal here is to build the best ganomede-directory on those technologies.

Some discussions...

**operational simplicity**

For operational simplicity: it is an order of magnitude more complex with Postgresql and Mariadb than with Couchdb. I'm not talking about deploying on a single host, but managing a live multi-hosts setup. Deploying with docker is super easy. But when load-balancing, hot-standby, automatic failover, monitoring, backup are easy with Couchdb, it's harder to setup and get right with postgres, maria/mysql. I won't enter into details as of why, I can give you pointers if you're interested by the subject.

I give operational simplicity the highest priority, because we want to spend as little time as possible on managing operations of past projects so we focus on the current/next ones.

**conflicts and replication**

When data is append-only, even with bidirectional synchronization, their is little room for conflicts in normal conditions: since you never edit or delete an existing document (thus you never create new revisions), just add new documents. The only possible conflict is trying to create simultaneously 2 **different** documents with the same ID to create a conflict. On our use-case it would be someone with a bad intension, not normal behavior.

Moreover, in our setup the http load balancer in front of Couchdb instances is configured to use URL based hashing, so documents with same ID will always be routed to the same instance (removing any risks of conflict), documents creation is always routed to the same instance.

**Comment by j3k0** [comment]
*About auth tokens*

Some context...

For now there's no complex setup. It's a single app (game1), auth tokens only used by this app (node microservice connect "directly" to Redis)... Yet, FYI, we have:

 - A few redis servers (1 master, N slaves) -- N=1 but this is not fixed (it changes when migrating or rebooting a host)
 - 3 redis sentinels that decide who the master is.
 - haproxy load balancers on each compute node, which routes traffic to the current redis master
   - node apps basically connect to some localhost port, it's routed to the right redis server

*Step 1*

After the winter grand update, we'll have 2 apps (game1 and game2). ganomede-* services will all access the same redis database.

*Step 2*

We will remove direct dependencies of ganomede-* over the redis authdb database, they'll ask "ganomede-directory" for token validation.

*Step 3*

"ganomede-directory" and a few other central services will be 100% isolated from game1 and game2. Only accessible through the REST API. We'll call this group of central services the "accounts" application.

The "accounts" application will be accessible to other apps/websites our client is will to develop (with or without fovea).

**Comment by elmigranto** [comment]
Closing this one, let's use #2.
