### ISSUE TITLE
Throws: Can not convert Profile to JSON directly

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-directory#25]
Warning showed on all get requests. What does it mean?

```
[2017-04-22T08:21:21.532Z] DEBUG: ganomede-directory/16 on f7542865abf7: directory.router.sendProfileBack (err=null)
    profile: [Throws: Can not convert Profile to JSON directly; use #public() or #private()]
```

**Comment by elmigranto** [comment]
Did this so that we don't accidentally `res.json(profile)` with password hash, etc. Not sure why is this a case, I believe I made it send either `#public()` or `#private()` with appropriate aliases based on access level.

**Comment by elmigranto** [comment]
Maybe it is printed when logging a profile object? Will need to `.debugInspect()` it instead then. Will take a look.
