### ISSUE TITLE
Add username suggestion script

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-directory#26]
**Usage:**

```
$ ./bin/find-alternative Alice
Alice013
```

```
$ ./bin/find-alternative AliceAlice
AliceAli43
```

**Pseudo algo:**

1. Given a username on the command line.
2. Generate a random alternative for this username, by adding a random digits in the end
    - Keep the username length <= 10, cut out the end of the existing username if necessary.
3. Check if there's already an existing user with `alias:tag` == `tagizer(alternative)`.
4. If there is, go back to 1. After 10 attempts, allow the alternative username generator to be more destructive of the original username (allow to change the to last 2 chars, then 3 chars, etc..)
5. Once an available alternative username is found display it.

**Notes**

Doesn't print anything else than the suggestion on stdout. Allowed to use stderr for debugging.

**Comment by j3k0** [comment]
See #27

**Comment by elmigranto** [comment]
Should it assume that passed in username can not be used?

**Comment by j3k0** [comment]
> Should it assume that passed in username can not be used?

It doesn't matter. Whatever is more convenient.
