### ISSUE TITLE
Handle renaming of users

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-directory#29]
In a moment of solitude, I realized renaming users will create issues if we don't also rename them in the redis `auth` database.

We need a script that preloads the list of "rename operations" contained in a CSV file, then iterates through all keys in the `auth` database to replace username that have been renamed.

#### General idea

 * For each renamed user
   * store usernames in a map `renames` containing "old &rArr; new"
 * For each key in `auth`
   * `GET key`  in `authdb`
   * parse the `object`
   * if `object` has been parsed OK and `renames[object.username]` is defined
     * set `object.username` to `renames[object.username]`
     * `SET key object` in `authdb`

#### renamed-users.csv

The batch renaming script generates a CSV file with fields:
```
email,oldUsername,newUsername
```

Example:
```
alice@email.com,alice,alice3
bob@email.com,bob12,bob120
```

#### auth database

Auth database contains auth tokens linked with a JSON string, with field username.

`auth token` &rArr; JSON object with field `username`

example:
```
GET "badc93248cd1f"
"{\"username\":\"numib171\"}"
```

#### Script usage

```
export REDIS_AUTH_PORT_6379_TCP_ADDR=127.0.0.1
export REDIS_AUTH_PORT_6379_TCP_PORT=12311
./bin/fix-authdb renamed-users.csv
```

**Comment by elmigranto** [comment]
Do we even allow changing a username? If so, couch is also in trouble since mostly everything is keyed as `userId:something[:subtype]` and have it in document somewhere as well.

**Comment by elmigranto** [comment]
Or do you mean `tag` aliases and how we sometimes (my suspicion it's not sometimes, but mostly always?) identify users with them?

**Comment by j3k0** [comment]
I wasn't very clear. I mean renaming while migrating a user from stormpath.

Necessary if one user was called jekO and another jek0. Same tag.

Renamed user isn't yet in the directory but has an entry in the auth database

**Comment by elmigranto** [comment]
Are headers part of CSV?

```
email,old,new
alice@wonderland.com,alice,alice01 
```

or is it just entries

```
alice@wonderland.com,alice,alice01
```

**Comment by elmigranto** [comment]
Also, how many tokens do we have (`DBSIZE`)? I assume it should be fine to run `KEYS`, but to be sure…

**Comment by elmigranto** [comment]
If I am not mistaken, we have `token => username: String` from earlier versions. Do we leave them as is?

**Comment by j3k0** [comment]
I believe all are `token &rArr; JSON`. A release candidate had token &rArr; username but was never deployed.

**Comment by j3k0** [comment]
`DBSIZE` pretty big (I guess around 500,000 -- will check this out)... however it's redis, so it fits in memory

**Comment by j3k0** [comment]
DBSIZE=850000
