### ISSUE TITLE
Add actions pre-checks to prevent most rollbacks

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-directory#4]
Make sure rollbacks are used as rarely as possible. Maybe a _check_ step ahead of executing the actions would be a good idea.

Pseudo-code:

```js
CreateUserIdAction = {
  execute: (cb) => // create some doc
  rollback: (cb) => // delete the doc
  check: (cb) => // fail if doc already exists
}
```

**Comment by elmigranto** [comment]
Closed in https://github.com/j3k0/ganomede-directory/commit/b1347ce727bfc95eaa96ee31778263bd17961546.

**Comment by j3k0** [comment]
You code faster than I write ;-)
