### ISSUE TITLE
API Responses

### ISSUE THREAD

**Issue by elmigranto** [j3k0/ganomede-directory#5]
There are some inconsistences in replies, for example, sometimes user ID is called `id` and some times it's `user_id`. Find all stuff like that, make it consistent, update README, but stick with what's there for now.

**Comment by j3k0** [comment]
If you are referring to the [find user by alias](https://github.com/j3k0/ganomede-directory#user-indexed-by-alias-directoryv1usersaliastypevalue) request, indeed it's a mistake: it should be "id" and not "user_id" to be consistent with the rest.

**Comment by elmigranto** [comment]
Okay, fixed that, there are also was stuff like timestamp in seconds instead of JS milliseconds, but it seems we removed that endpoint, and don't really accept dates anywhere by using server-time instead. So this can probably be closed then.
